# Generated by Django 4.1.7 on 2023-04-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="photograph",
        ),
    ]
