# Generated by Django 4.1.7 on 2023-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("warden", "Warden"),
                    ("hall_clerk", "Hall Clerk"),
                    ("hmc_chairman", "HMC Chairman"),
                    ("mess_manager", "Mess Manager"),
                    ("admin", "Administrator"),
                    ("admission", "AdmissionUnit"),
                ],
                default="student",
                max_length=40,
                verbose_name="Role",
            ),
        ),
    ]
