# Generated by Django 4.1.7 on 2023-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenityroom",
            name="rent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Rent"
            ),
        ),
        migrations.AlterField(
            model_name="boarderroom",
            name="rent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Rent"
            ),
        ),
    ]
