# Generated by Django 4.1.7 on 2023-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boarderroom",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
