# Generated by Django 4.1.7 on 2023-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_amenityroom_rent_alter_boarderroom_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messaccount",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Update Date"),
        ),
    ]
