# Generated by Django 4.1.7 on 2023-04-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_boarderroom_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessAccount",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="messAccount",
                        serialize=False,
                        to="main.student",
                    ),
                ),
                (
                    "due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Mess Due",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="boarderroom",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
