# Generated by Django 4.1.7 on 2023-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_boarderroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarderroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
