# Generated by Django 4.1.7 on 2023-04-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_messaccounthistory_messaccount_last_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messaccounthistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="messaccounthistory",
            name="mess_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mess_account_history",
                to="main.messaccount",
            ),
        ),
    ]
