# Generated by Django 4.1.7 on 2023-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_amenityroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='total_amenityrooms',
            field=models.IntegerField(default=0, verbose_name='Total Rooms'),
        ),
    ]
