# Generated by Django 4.1.7 on 2023-04-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_hallpassbook_alter_person_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photograph",
            field=models.ImageField(blank=True, upload_to="", verbose_name="Photo"),
        ),
        migrations.AlterField(
            model_name="pettyexpense",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="salaryexpense",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="Timestamp"),
        ),
    ]
