# Generated by Django 4.1.7 on 2023-04-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_messaccounthistory_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Due",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "demand",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Demand"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mess", "Mess Due"),
                            ("boarderRoom", "Boarder Room Due"),
                            ("amenityRooms", "Amenity Rooms Due"),
                        ],
                        default="mess",
                        max_length=100,
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passbook",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="passbook",
                        serialize=False,
                        to="main.student",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="rollNumber",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Roll Number"
            ),
        ),
        migrations.DeleteModel(
            name="MessAccountHistory",
        ),
        migrations.AddField(
            model_name="due",
            name="passbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dues",
                to="main.passbook",
            ),
        ),
    ]
