# Generated by Django 4.1.7 on 2023-04-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messaccount_alter_boarderroom_id'),
        ('main', '0006_alter_amenityroom_hall_alter_hall_total_amenityrooms'),
    ]

    operations = [
    ]
