# Generated by Django 4.1.7 on 2023-04-09 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_person_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atr',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='atr',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 7, 4, 37, 856739)),
            preserve_default=False,
        ),
    ]
