# Generated by Django 4.1.7 on 2023-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_messaccounthistory_id_and_more"),
        ("main", "0007_merge_20230406_1617"),
    ]

    operations = []
