# Generated by Django 4.1.7 on 2023-04-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_hall_total_rooms_hall_total_boarderrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintRegister',
            fields=[
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='complaint_register', serialize=False, to='main.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('nameagainst', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('complaintregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_complaints', to='main.complaintregister')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_complaints', to='main.student')),
            ],
        ),
    ]
