# Generated by Django 4.1.7 on 2023-04-07 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_complaintregister_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATR',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ATR', serialize=False, to='main.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='warden', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warden', to='main.hall')),
            ],
        ),
    ]
